export const backgroundMap = {
  demo_SubBU: {
    Label: 'Sub-business unit',
    Answers: {
      SubBU_1: ['General Management'],
      SubBU_2: ['Marketing Department'],
      SubBU_3: ['Operations Department'],
      SubBU_4: ['Finance Department'],
      SubBU_5: ['Sales Department'],
      SubBU_6: ['Human Resource Department'],
      SubBU_7: ['Purchase Department'],
      SubBU_8: ['Quality Control Department'],
      SubBU_9: ['Expediting Department'],
      SubBU_10: ['Engineering Department'],
      SubBU_11: ['Projects Department'],
      SubBU_12: ['Corporate Communications'],
      SubBU_13: ['Overseas Projects Department'],
      SubBU_14: ['Customer Service'],
      SubBU_15: ['Other'],
    },
  },
  demo_Region: {
    Label: 'Region',
    Answers: {
      Region_1: ['Asia Pacific'],
      Region_2: ['Latin America (including Mexico, Central and South America)', 'Latin America'],
      Region_3: ['EMEA'],
      Region_4: ['North America (USA & Canada)', 'North America'],
    },
  },
  demo_Ethnicity: {
    Label: 'Ethnicity',
    Answers: {
      Ethnicity_1: [
        'American Indian/Alaska Native (origins in any of the original peoples of North and South America (including Central America) and who maintains tribal affiliation or community attachment)',
        'American Indian',
        'Alaska Native',
      ],
      Ethnicity_2: [
        'Asian (origins in any original peoples of Far East, Southeast Asia, or Indian subcontinent)',
        'Asian',
      ],
      Ethnicity_3: [
        'Black African American (origins in any of the Black racial groups of Africa)',
        'African American',
        'Black African American',
      ],
      Ethnicity_4: ['Hispanic/Latino', 'Hispanic', 'Latino'],
      Ethnicity_5: ['Two or More Race', 'multi'],
      Ethnicity_6: [
        'Native Hawaiian/Oth Pac Island (A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands)',
        'Native Hawaiian',
        'Hawaiian',
        'Oth Pac Island',
      ],
      Ethnicity_7: [
        'White (origins in any of the original peoples of Europe, the Middle East, or North Africa)',
      ],
      Ethnicity_8: ['Not listed'],
      Ethnicity_9: ['White'],
      Ethnicity_10: ['Black'],
      Ethnicity_11: ['Brown'],
      Ethnicity_12: ['Asian (Yellow)', 'Asian', 'Yellow'],
      Ethnicity_13: ['Indigenous'],
      Ethnicity_14: ['Biracial (Mestizo)', 'Mestizo', 'Biracial'],
      Ethnicity_15: ['Others'],
      Ethnicity_999: ['Prefer not to say'],
    },
  },
  demo_AgeYear: {
    Label: 'Birth Year',
    Answers: {
      AgeYear_1: ['Born in 1945 or before', 'Before 1945'],
      AgeYear_2: ['1946 - 1964'],
      AgeYear_3: ['1965 - 1980'],
      AgeYear_4: ['1981 - 1996'],
      AgeYear_5: ['1996 and onward', 'After 1996'],
      AgeYear_999: ['Prefer not to say'],
    },
  },
  demo_Gender: {
    Label: 'Gender',
    Answers: {
      Gender_1: ['Male'],
      Gender_2: ['Female'],
      Gender_3: ['Non-binary / Gender Fluid', 'Non-binary', 'Gender Fluid'],
      Gender_4: ['A gender not listed', 'Not listed'],
      Gender_999: ['Prefer not to say'],
    },
  },
  demo_SexOrientation: {
    Label: 'Sexual Orientation',
    Answers: {
      SexOrientation_1: ['Gay, lesbian, or homosexual', 'Gay', 'lesbian', 'homosexual'],
      SexOrientation_2: ['Bisexual or pansexual', 'Bisexual', 'pansexual'],
      SexOrientation_3: ['Heterosexual or straight', 'Heterosexual', 'Straight'],
      SexOrientation_4: ['Other'],
      SexOrientation_999: ['Prefer not to say'],
    },
  },
  demo_Tenure: {
    Label: 'Years at Organization',
    Answers: {
      Tenure_1: ['Less than 1 year'],
      Tenure_2: ['1 to <3 years'],
      Tenure_3: ['3 to <6 years'],
      Tenure_4: ['6 to <11 years'],
      Tenure_5: ['11 to <20 years'],
      Tenure_6: ['20 years or more'],
    },
  },
  demo_Level: {
    Label: 'Job level',
    Answers: {
      Level_1: ['Executive Team'],
      Level_2: ['Top Management'],
      Level_3: ['Middle Management'],
      Level_4: ['Front-line Management'],
      Level_5: ['Non-Management Individual contributors'],
      Level_6: ['Frontline worker'],
    },
  },
  demo_Function: {
    Label: 'Job Function',
    Answers: {
      Function_1: [
        'Business development / mergers and acquisitions',
        'Business development',
        'mergers and acquisitions',
      ],
      Function_2: ['Communications'],
      Function_3: ['Compliance / quality assurance', 'quality assurance', 'Compliance'],
      Function_4: ['Customer service'],
      Function_5: ['Finance'],
      Function_6: ['General management, not otherwise classified', 'General management'],
      Function_7: ['Healthcare worker - Doctor', 'Doctor'],
      Function_8: ['Healthcare worker non - Doctor (e.g., Nurses)', 'Nurse'],
      Function_9: ['Human resources', 'HR'],
      Function_10: ['Information technology', 'IT'],
      Function_11: ['Legal'],
      Function_12: ['Maintenance'],
      Function_13: ['Operations'],
      Function_14: ['Operations support functions'],
      Function_15: ['Performance management office'],
      Function_16: ['Protective services (e.g., Police, Fire)', 'Police', 'Fire'],
      Function_17: ['Research and development', 'RnD', 'R&D'],
      Function_18: ['Risk'],
      Function_19: ['Safety'],
      Function_20: ['Sales and marketing', 'Sales', 'Marketing'],
      Function_21: ['Shared services / support staff', 'Shared services', 'support staff'],
      Function_22: ['Strategy / strategic planning', 'Strategy', 'strategic planning'],
      Function_23: ['Supply chain / purchasing / procurement', 'Supply chain', 'purchasing'],
      Function_24: ['Trading'],
      Function_25: ['Other, not listed', 'Other', 'not listed'],
    },
  },
  demo_Location: {
    Label: 'Location',
    Answers: {
      Location_1: ['Afghanistan'],
      Location_2: ['Albania'],
      Location_3: ['Algeria'],
      Location_4: ['Andorra'],
      Location_5: ['Angola'],
      Location_6: ['Antigua & Deps'],
      Location_7: ['Argentina'],
      Location_8: ['Armenia'],
      Location_9: ['Australia'],
      Location_10: ['Austria'],
      Location_11: ['Azerbaijan'],
      Location_12: ['Bahamas'],
      Location_13: ['Bahrain'],
      Location_14: ['Bangladesh'],
      Location_15: ['Barbados'],
      Location_16: ['Belarus'],
      Location_17: ['Belgium'],
      Location_18: ['Belize'],
      Location_19: ['Benin'],
      Location_20: ['Bhutan'],
      Location_21: ['Bolivia'],
      Location_22: ['Bosnia Herzegovina', 'Bosnia'],
      Location_23: ['Botswana'],
      Location_24: ['Brazil'],
      Location_25: ['Brunei'],
      Location_26: ['Bulgaria'],
      Location_27: ['Burkina'],
      Location_28: ['Burundi'],
      Location_29: ['Cambodia'],
      Location_30: ['Cameroon'],
      Location_31: ['Canada'],
      Location_32: ['Cape Verde'],
      Location_33: ['Central African Rep'],
      Location_34: ['Chad'],
      Location_35: ['Chile'],
      Location_36: ['China'],
      Location_37: ['Colombia'],
      Location_38: ['Comoros'],
      Location_39: ['Congo'],
      Location_40: ['Congo (Democratic Rep)', 'Congo'],
      Location_41: ['Costa Rica'],
      Location_42: ['Croatia'],
      Location_43: ['Cuba'],
      Location_44: ['Cyprus'],
      Location_45: ['Czech Republic'],
      Location_46: ['Denmark'],
      Location_47: ['Djibouti'],
      Location_48: ['Dominica'],
      Location_49: ['Dominican Republic'],
      Location_50: ['East Timor'],
      Location_51: ['Ecuador'],
      Location_52: ['Egypt'],
      Location_53: ['El Salvador'],
      Location_54: ['Equatorial Guinea'],
      Location_55: ['Eritrea'],
      Location_56: ['Estonia'],
      Location_57: ['Ethiopia'],
      Location_58: ['Fiji'],
      Location_59: ['Finland'],
      Location_60: ['France'],
      Location_61: ['Gabon'],
      Location_62: ['Gambia'],
      Location_63: ['Georgia'],
      Location_64: ['Germany'],
      Location_65: ['Ghana'],
      Location_66: ['Greece'],
      Location_67: ['Grenada'],
      Location_68: ['Guatemala'],
      Location_69: ['Guinea'],
      Location_70: ['Guinea-Bissau'],
      Location_71: ['Guyana'],
      Location_72: ['Haiti'],
      Location_73: ['Honduras'],
      Location_74: ['Hungary'],
      Location_75: ['Iceland'],
      Location_76: ['India'],
      Location_77: ['Indonesia'],
      Location_78: ['Iran'],
      Location_79: ['Iraq'],
      Location_80: ['Ireland (Republic)', 'Ireland'],
      Location_81: ['Israel'],
      Location_82: ['Italy'],
      Location_83: ['Ivory Coast'],
      Location_84: ['Jamaica'],
      Location_85: ['Japan'],
      Location_86: ['Jordan'],
      Location_87: ['Kazakhstan'],
      Location_88: ['Kenya'],
      Location_89: ['Kiribati'],
      Location_90: ['Korea North', 'North Korea'],
      Location_91: ['Korea South', 'South Korea'],
      Location_92: ['Kuwait'],
      Location_93: ['Kyrgyzstan'],
      Location_94: ['Laos'],
      Location_95: ['Latvia'],
      Location_96: ['Lebanon'],
      Location_97: ['Lesotho'],
      Location_98: ['Liberia'],
      Location_99: ['Libya'],
      Location_100: ['Liechtenstein'],
      Location_101: ['Lithuania'],
      Location_102: ['Luxembourg'],
      Location_103: ['Macedonia'],
      Location_104: ['Madagascar'],
      Location_105: ['Malawi'],
      Location_106: ['Malaysia'],
      Location_107: ['Maldives'],
      Location_108: ['Mali'],
      Location_109: ['Malta'],
      Location_110: ['Marshall Islands'],
      Location_111: ['Mauritania'],
      Location_112: ['Mauritius'],
      Location_113: ['Mexico'],
      Location_114: ['Micronesia'],
      Location_115: ['Moldova'],
      Location_116: ['Monaco'],
      Location_117: ['Mongolia'],
      Location_118: ['Montenegro'],
      Location_119: ['Morocco'],
      Location_120: ['Mozambique'],
      Location_121: ['Myanmar (Burma)', 'Myanmar', 'Burma'],
      Location_122: ['Namibia'],
      Location_123: ['Nauru'],
      Location_124: ['Nepal'],
      Location_125: ['Netherlands'],
      Location_126: ['New Zealand'],
      Location_127: ['Nicaragua'],
      Location_128: ['Niger'],
      Location_129: ['Nigeria'],
      Location_130: ['Norway'],
      Location_131: ['Oman'],
      Location_132: ['Pakistan'],
      Location_133: ['Palau'],
      Location_134: ['Panama'],
      Location_135: ['Papua New Guinea'],
      Location_136: ['Paraguay'],
      Location_137: ['Peru'],
      Location_138: ['Philippines'],
      Location_139: ['Poland'],
      Location_140: ['Portugal'],
      Location_141: ['Qatar'],
      Location_142: ['Romania'],
      Location_143: ['Russian Federation', 'Russia'],
      Location_144: ['Rwanda'],
      Location_145: ['St Kitts & Nevis'],
      Location_146: ['St Lucia'],
      Location_147: ['Saint Vincent & the Grenadines'],
      Location_148: ['Samoa'],
      Location_149: ['San Marino'],
      Location_150: ['Sao Tome & Principe'],
      Location_151: ['Saudi Arabia'],
      Location_152: ['Senegal'],
      Location_153: ['Serbia'],
      Location_154: ['Seychelles'],
      Location_155: ['Sierra Leone'],
      Location_156: ['Singapore'],
      Location_157: ['Slovakia'],
      Location_158: ['Slovenia'],
      Location_159: ['Solomon Islands'],
      Location_160: ['Somalia'],
      Location_161: ['South Africa'],
      Location_162: ['Spain'],
      Location_163: ['Sri Lanka'],
      Location_164: ['Sudan'],
      Location_165: ['Suriname'],
      Location_166: ['Swaziland'],
      Location_167: ['Sweden'],
      Location_168: ['Switzerland'],
      Location_169: ['Syria'],
      Location_170: ['Taiwan'],
      Location_171: ['Tajikistan'],
      Location_172: ['Tanzania'],
      Location_173: ['Thailand'],
      Location_174: ['Togo'],
      Location_175: ['Tonga'],
      Location_176: ['Trinidad & Tobago'],
      Location_177: ['Tunisia'],
      Location_178: ['Turkey'],
      Location_179: ['Turkmenistan'],
      Location_180: ['Tuvalu'],
      Location_181: ['Uganda'],
      Location_182: ['Ukraine'],
      Location_183: ['United Arab Emirates', 'UAE'],
      Location_184: ['United Kingdom', 'UK'],
      Location_185: ['United States', 'US', 'USA', 'United States of America'],
      Location_186: ['Uruguay'],
      Location_187: ['Uzbekistan'],
      Location_188: ['Vanuatu'],
      Location_189: ['Vatican City'],
      Location_190: ['Venezuela'],
      Location_191: ['Vietnam'],
      Location_192: ['Yemen'],
      Location_193: ['Zambia'],
      Location_194: ['Zimbabwe'],
    },
  },
};
